### PR TITLE
applied google's clang format

### PR DESCRIPTION
**Pull request by mkalkbrenner**
Before I start to migrate PPUC's threading model and PIN2DMD support to libdmdutil, it would be important to ensure a common coding style.
This PR applies google's coding standard, the one we agreed on for libserum, libzedmd, libppuc, ...
And I changed all line endings to LF to be consistent within the project.

### CODE REVIEW

**Comment by mkalkbrenner** [comment]
https://google.github.io/styleguide/cppguide.html

**Comment by toxieainc** [comment]
Static analysis is kinda orthogonal to coding guidelines/formatting.

For vpinball and pinmame we have no real guidelines/common formatting yet, only 'adapt to guidelines/formatting of surrounding code to be locally consistent'. And i'm against unifying it as an afterthought, as then the blame functionality is always (at least) one more step complicated.
But as libdmdutil is still so new it will not matter much, so if there is already a 'standard' between 'neighboring' libs please go ahead with that.

**Review by toxieainc — APPROVED** [review]
I'm no big fan of such things, but also don't care much.

**Comment by toxieainc** [comment]
One additional comment @jsm174 @mkalkbrenner now that i see the changes in practice.
Is it really necessary to limit line lengths that harshly in 2024, 4k screens and all?  ;)
So that part i would personally change again.

**Comment by mkalkbrenner** [comment]
I just applied a a coding style that is available out of the box. But for sure we can adjust the clang format file according to our needs.

**Comment by jsm174** [comment]
I have a really hard time with super super super short lines like this one does out of the box as well.

**Comment by mkalkbrenner** [comment]
@jsm174 @toxieainc
So what is the conclusion? Raising the limit but keeping the other rules?

**Comment by toxieainc** [comment]
I personally would vote for 120.

Plus i personally prefer BreakBeforeBraces Allman (=always do a linebreak before braces), but i know that this setting in general is always debated. At least from my own experience (ranging from tiny open source projects to double-digit-million-line professional projects) this was and is the most common though.

If any of these is applied, i guess best would be to revert to pre-PR state and then apply, otherwise some existing new linebreaks may be kept?

**Comment by jsm174** [comment]
I can do that.

So just to confirm:

```
BreakBeforeBraces: Allman
ColumnLimit: 120
```

**Comment by jsm174** [comment]
@toxieainc @mkalkbrenner  - can you take a look at https://github.com/vpinball/libdmdutil/commit/640912bac1c509d5149788142e50064a30c1cc03

I used the source from https://github.com/vpinball/libdmdutil/commit/b300cd64060b3dd995341087b22a83f414f8b513 so immediately before the first apply. I think thats what you were asking to do.

**Comment by toxieainc** [comment]
Looks better, yes, thanks!
IMHO there is only one piece that looks worse now: AlphaNumeric::SegSizes definition. But thats negligible.

**Comment by jsm174** [comment]
there might be a way to suppress clang format with a tag or something. I will check

**Comment by jsm174** [comment]
@toxieainc - pushed again with `// clang-format off` and `// clang-format on`

**Comment by toxieainc** [comment]
Neat, thanks!!

**Pull request merged**
