### PR TITLE
Serum2

### PR DESCRIPTION
**Pull request by mkalkbrenner**

### CODE REVIEW

**Comment by mkalkbrenner** [comment]
The included tests run on ZeDMD and Pixelcade. But using libpinmame with Serum V1 crashes. So some more debugging is required...

**Comment by jsm174** [comment]
I think mac runners might be arm64 now, which is why the test might have failed. Have to research...

**Comment by jsm174** [comment]
we could probably use `uname -m` to detect

**Comment by francisdb** [comment]
Yes, you can now set the architecture on the runners.

**Comment by jsm174** [comment]
No, we can keep these on macos-14. Building is not an issue.

**Comment by jsm174** [comment]
@mkalkbrenner  - truly amazing work!!

**Comment by PastorL69** [comment]
Markus, take a break .. 😂

**Pull request merged**
